### ISSUE TITLE
plotting issue

### ISSUE THREAD

**Issue by andrewczgithub** [tonyduan/normalizing-flows#3]
Hi @tonyduan !

love the library.

I am getting an error on the plotting.

I was also wondering if its possible to add a jupyter notebook.
Kind regards,
Andrew 

``python
plotlib.font_manager:findfont: score(<Font 'Liberation Sans' (LiberationSans-Bold.ttf) normal normal bold normal>) = 10.335
DEBUG:matplotlib.font_manager:findfont: score(<Font 'Source Code Pro' (SourceCodePro-Semibold.otf) normal normal semibold normal>) = 10.24
DEBUG:matplotlib.font_manager:findfont: score(<Font 'Droid Arabic Kufi' (DroidKufi-Bold.ttf) normal normal bold normal>) = 10.335
DEBUG:matplotlib.font_manager:findfont: Matching :family=sans-serif:style=normal:variant=normal:weight=normal:stretch=normal:size=12.0 to DejaVu Sans ('/home/andrewcz/tutorial-env11/lib/python3.7/site-packages/matplotlib/mpl-data/fonts/ttf/DejaVuSans.ttf') with score of 0.050000.
Traceback (most recent call last):
  File "flow_1d.py", line 78, in <module>
    plt.savefig("./examples/ex_1d.png")
  File "/home/andrewcz/tutorial-env11/lib/python3.7/site-packages/matplotlib/pyplot.py", line 722, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/home/andrewcz/tutorial-env11/lib/python3.7/site-packages/matplotlib/figure.py", line 2180, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/home/andrewcz/tutorial-env11/lib/python3.7/site-packages/matplotlib/backend_bases.py", line 2089, in print_figure
    **kwargs)
  File "/home/andrewcz/tutorial-env11/lib/python3.7/site-packages/matplotlib/backends/backend_agg.py", line 530, in print_png
    cbook.open_file_cm(filename_or_obj, "wb") as fh:
  File "/usr/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/home/andrewcz/tutorial-env11/lib/python3.7/site-packages/matplotlib/cbook/__init__.py", line 447, in open_file_cm
    fh, opened = to_filehandle(path_or_file, mode, True, encoding)
  File "/home/andrewcz/tutorial-env11/lib/python3.7/site-packages/matplotlib/cbook/__init__.py", line 432, in to_filehandle
    fh = open(fname, flag, encoding=encoding)
FileNotFoundError: [Errno 2] No such file or directory: './examples/ex_1d.png'

``

**Comment by tonyduan** [comment]
@andrewczgithub Haven't seen this before but a few quick thoughts:

1. How are running the code? It should be: `python3 -m examples.ex_1d`.
2. You can create a new Jupyter notebook in the base directory, copy all the code in one of the examples files, and run it. This should work as well.
